### ISSUE TITLE
Sort by member name?

### ISSUE THREAD

**Issue by lonix1** [kokoabim/vscode-csharpen#3]
Nice extension! :+1: 

I'd like to convert this:
```cs
public const string NAME_CUSTOMER = "Foo";
public DateTime Created { get; }
public IDictionary<long, long> Mapping { get; }
private readonly Product _product;
public double Price { get; }
```

To this:
```cs
private readonly Product _product;
public DateTime Created { get; }
public IDictionary<long, long> Mapping { get; }
public const string NAME_CUSTOMER = "Foo";
public double Price { get; }
```

Notice how it sorts by member name. The default vscode sort action sorts entire lines. 

This extension has so many options, so I couldn't figure it out. Is it possible?

**Comment by kokoabim** [comment]
Thanks. I'll take a look at this.

**Comment by kokoabim** [comment]
First off, when sorting, it _does_ use the member name, not the "line as-is".

**Comment by kokoabim** [comment]
I don't know your settings as well as when is the outcome you're seeing (though I take it the outcome isn't what you're looking for).

**Comment by kokoabim** [comment]
Here is what I am seeing, with default settings with (soon-to-be released next version, which really is a clean up of default settings triggered by this issue, shouldn't differ much if at all, basically just explicitly defined defaults).

Starting with this...
```csharp
namespace CSharpDotNetProject;

public class TypeMemberName
{
    public const string NAME_CUSTOMER = "Foo";
    public DateTime Created { get; }
    public IDictionary<long, long> Mapping { get; }
    private readonly Product _product;
    public double Price { get; }
}

class Product
{
}
```

Upon _sharpening_, it becomes:
```csharp
namespace CSharpDotNetProject;

public class TypeMemberName
{
    public const string NAME_CUSTOMER = "Foo";

    #region properties
    public DateTime Created { get; }
    public IDictionary<long, long> Mapping { get; }
    public double Price { get; }
    #endregion 

    private readonly Product _product;
}

class Product
{
}
```

**Comment by lonix1** [comment]
> First off, when sorting, it does use the member name, not the "line as-is".

I was referring to vscode itself.

Thanks for the example. Is there a way for them to be shown like in the example I posted above (only sorting, no grouping)?

**Comment by kokoabim** [comment]
See the regionalize settings. Closing as pertains to settings.
